Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)
Chat.say("#sel ca")
Client.waitTick(1000)
Chat.say("#explore")
Client.waitTick(50)


